### ISSUE TITLE
setup-gce always selects "default" network

### ISSUE THREAD

**Issue by tpdownes** [UnivaCorporation/tortuga-kit-gceadapter#116]
Consider instead detecting the network in use by the machine. _e.g._
```
[tdownes@launch ~]$ facter gce.instance.networkInterfaces.0.network
launch-demo-network
```
Also accessible via `curl` interface.

**Comment by dtougas** [comment]
That's a good idea, though we would still need to have a fallback to `default` for the case where the installer is not physically on the GCE network.

**Comment by tpdownes** [comment]
I have discovered along the way that, if you don't "auto" create subnetworks, then you have to manually specify the subnetwork in the adapter/GCP API. The subnetwork is (so far as I can tell) not available in the instance metadata.

So specifying either `default` or `network` alone are both the wrong things in this instance. One fails by deploying an instance into the (useless) default network while the other fails on the API call.

For now, consider this a place-holder issue for discussing potential changes along these lines.
