### ISSUE TITLE
setup-gce should support fallback to service account credentials

### ISSUE THREAD

**Issue by tpdownes** [UnivaCorporation/tortuga-kit-gceadapter#82]
Both [the code](https://github.com/UnivaCorporation/tortuga-kit-gceadapter/blob/master/src/tortuga/resourceAdapter/gceadapter/gce.py#L2052) and my observed behavior of the GCE resource adapter suggests that it successfully falls back to service account credentials attached to an instance. The `setup-gce` script should, too, by providing a warning rather than failing outright if the JSON key file does not exist. In this case, it would not populate the configuration field that points to the key file.

In my view, initial setup is greatly simplified by allowing users to create/use a single service account they can reuse with demo instances.

**Comment by dtougas** [comment]
Fixed, as suggested.
